services:
  pgAdmin:
    container_name: pg-dashboard
    environment:
      - PGADMIN_DEFAULT_EMAIL=aymen.dragon5@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=aymen77
    image: dpage/pgadmin4
    ports:
      - '9097:80'
      - '9092:443'
    networks:
      - ktouryNetwork
    depends_on:
      - postgresDB

  postgresDB:
    container_name: ktoury-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ktoury-db
    ports:
      - '5432:5432'
    networks:
      - ktouryNetwork
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    networks:
      - ktouryNetwork

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8088:8080"
    command:
      - start-dev

  ktoury:
    image: droidzed/ktoury:${IMAGE_TAG}
    container_name: ktoury-server
    ports:
      - '8080:8080'
    networks:
      - ktouryNetwork
    depends_on:
      - pgAdmin
      - postgresDB
      - redis
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ktoury-db:5432/ktoury-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  database:
networks:
  ktouryNetwork:
    driver: bridge
